# Generated by Django 3.2.5 on 2022-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='links',
        ),
        migrations.AddField(
            model_name='video',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
