# Generated by Django 3.2.5 on 2022-01-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220107_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_delete',
        ),
    ]
