# Generated by Django 3.2.5 on 2022-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_video_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
